/* =========================================================
   Task 4: SQL Intermediate – JOINs using Chinook Database
   Database: Chinook_Sqlite.sqlite
   Tool: DB Browser for SQLite
   ========================================================= */


/* ---------------------------------------------------------
   1. INNER JOIN
   Purpose:
   - Combine Customer and Invoice tables
   - Show only customers who have placed orders
   - Used to analyze active customers and sales
   --------------------------------------------------------- */

SELECT
    c.FirstName,
    c.LastName,
    i.InvoiceId,
    i.InvoiceDate,
    i.Total
FROM Customer c
INNER JOIN Invoice i
ON c.CustomerId = i.CustomerId;


/* ---------------------------------------------------------
   2. LEFT JOIN
   Purpose:
   - Find customers who have NEVER placed any orders
   - Important for business marketing and customer retention
   --------------------------------------------------------- */

SELECT 
    c.CustomerId,
    c.FirstName,
    c.LastName
FROM Customer c
LEFT JOIN Invoice i
ON c.CustomerId = i.CustomerId
WHERE i.InvoiceId IS NULL;


/* ---------------------------------------------------------
   3. Revenue per Track (Product-level Analysis)
   Purpose:
   - Join InvoiceLine and Track tables
   - Calculate total revenue generated by each track
   - Identify top-performing products
   --------------------------------------------------------- */

SELECT 
    t.Name AS TrackName,
    SUM(ii.UnitPrice * ii.Quantity) AS Revenue
FROM InvoiceLine ii
INNER JOIN Track t
ON ii.TrackId = t.TrackId
GROUP BY t.Name
ORDER BY Revenue DESC;


/* ---------------------------------------------------------
   4. Revenue by Genre (Category-wise Analysis)
   Purpose:
   - Join InvoiceLine, Track, and Genre tables
   - Calculate total revenue for each music genre
   - Used for category and business strategy decisions
   --------------------------------------------------------- */

SELECT 
    g.Name AS Genre,
    SUM(ii.UnitPrice * ii.Quantity) AS Revenue
FROM InvoiceLine ii
INNER JOIN Track t
ON ii.TrackId = t.TrackId
INNER JOIN Genre g
ON t.GenreId = g.GenreId
GROUP BY g.Name;


/* ========================= END =========================== */
